<?php

use Drupal\Core\Template\Attribute;
use Drupal\Component\Utility\Html;

/**
 * @file
 * Primary module hooks for castle_components module.
 */


 /**
 * Implements hook_library_info_build().
 */
// function castle_components_library_info_alter(&$libraries, $extension) {}


/**
 * Prepares variables for views-style-castle-components-castle-grid.html.twig template.
 */
function template_preprocess_views_style_castle_components_castle_grid(array &$variables): void {
  $view = $variables['view'];
  $rows = $variables['rows'];
  $variables['options'] = $view->style_plugin->options;
  $utilities = [];
  if (isset($variables['options']['utility_classes'])) {
    $classes = explode(' ', $variables['options']['utility_classes']);
    foreach ($classes as &$class) {
      $utilities[] = Html::cleanCssIdentifier($class);
    }
  }
  $variables['options']['utility_classes'] = $utilities;
  foreach ($rows as $key => $row) {
    $variables['rows'][$key] = [];
    $variables['rows'][$key]['content'] = $row;
    $variables['rows'][$key]['attributes'] = new Attribute();
  }
}
